# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../_sources_ui/Menu/menu.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName(_fromUtf8("Menu"))
        Menu.resize(1000, 730)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Menu.sizePolicy().hasHeightForWidth())
        Menu.setSizePolicy(sizePolicy)
        Menu.setMinimumSize(QtCore.QSize(1000, 730))
        Menu.setMaximumSize(QtCore.QSize(1000, 730))
        self.ZoneCentrale = QtGui.QWidget(Menu)
        self.ZoneCentrale.setObjectName(_fromUtf8("ZoneCentrale"))
        self.FondIcone = QtGui.QGraphicsView(self.ZoneCentrale)
        self.FondIcone.setGeometry(QtCore.QRect(40, 40, 921, 261))
        self.FondIcone.setObjectName(_fromUtf8("FondIcone"))
        self.LabelChoisissez = QtGui.QLabel(self.ZoneCentrale)
        self.LabelChoisissez.setGeometry(QtCore.QRect(280, 320, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LabelChoisissez.setFont(font)
        self.LabelChoisissez.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelChoisissez.setObjectName(_fromUtf8("LabelChoisissez"))
        self.FrameTempsJeu = QtGui.QFrame(self.ZoneCentrale)
        self.FrameTempsJeu.setGeometry(QtCore.QRect(510, 370, 451, 91))
        self.FrameTempsJeu.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrameTempsJeu.setFrameShadow(QtGui.QFrame.Plain)
        self.FrameTempsJeu.setObjectName(_fromUtf8("FrameTempsJeu"))
        self.LabelTempsJeuT = QtGui.QLabel(self.FrameTempsJeu)
        self.LabelTempsJeuT.setGeometry(QtCore.QRect(20, 20, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelTempsJeuT.setFont(font)
        self.LabelTempsJeuT.setObjectName(_fromUtf8("LabelTempsJeuT"))
        self.LabelTempsJeuMinutes = QtGui.QLabel(self.FrameTempsJeu)
        self.LabelTempsJeuMinutes.setGeometry(QtCore.QRect(120, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelTempsJeuMinutes.setFont(font)
        self.LabelTempsJeuMinutes.setObjectName(_fromUtf8("LabelTempsJeuMinutes"))
        self.LabelTempsJeuSecondes = QtGui.QLabel(self.FrameTempsJeu)
        self.LabelTempsJeuSecondes.setGeometry(QtCore.QRect(330, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelTempsJeuSecondes.setFont(font)
        self.LabelTempsJeuSecondes.setObjectName(_fromUtf8("LabelTempsJeuSecondes"))
        self.LabelTempsColon = QtGui.QLabel(self.FrameTempsJeu)
        self.LabelTempsColon.setGeometry(QtCore.QRect(190, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LabelTempsColon.setFont(font)
        self.LabelTempsColon.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelTempsColon.setObjectName(_fromUtf8("LabelTempsColon"))
        self.SBoxMinutes = QtGui.QSpinBox(self.FrameTempsJeu)
        self.SBoxMinutes.setGeometry(QtCore.QRect(20, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SBoxMinutes.setFont(font)
        self.SBoxMinutes.setAlignment(QtCore.Qt.AlignCenter)
        self.SBoxMinutes.setMaximum(10)
        self.SBoxMinutes.setSingleStep(1)
        self.SBoxMinutes.setProperty("value", 1)
        self.SBoxMinutes.setObjectName(_fromUtf8("SBoxMinutes"))
        self.SBoxSecondes = QtGui.QSpinBox(self.FrameTempsJeu)
        self.SBoxSecondes.setGeometry(QtCore.QRect(230, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SBoxSecondes.setFont(font)
        self.SBoxSecondes.setAlignment(QtCore.Qt.AlignCenter)
        self.SBoxSecondes.setMaximum(50)
        self.SBoxSecondes.setSingleStep(10)
        self.SBoxSecondes.setObjectName(_fromUtf8("SBoxSecondes"))
        self.FrameSource = QtGui.QFrame(self.ZoneCentrale)
        self.FrameSource.setGeometry(QtCore.QRect(40, 370, 451, 321))
        self.FrameSource.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrameSource.setFrameShadow(QtGui.QFrame.Raised)
        self.FrameSource.setObjectName(_fromUtf8("FrameSource"))
        self.LabelSource = QtGui.QLabel(self.FrameSource)
        self.LabelSource.setGeometry(QtCore.QRect(20, 20, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelSource.setFont(font)
        self.LabelSource.setObjectName(_fromUtf8("LabelSource"))
        self.TabSourceTexte = QtGui.QTabWidget(self.FrameSource)
        self.TabSourceTexte.setGeometry(QtCore.QRect(20, 50, 411, 251))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TabSourceTexte.setFont(font)
        self.TabSourceTexte.setObjectName(_fromUtf8("TabSourceTexte"))
        self.TabSpeciaux = QtGui.QWidget()
        self.TabSpeciaux.setObjectName(_fromUtf8("TabSpeciaux"))
        self.Sep1 = QtGui.QFrame(self.TabSpeciaux)
        self.Sep1.setGeometry(QtCore.QRect(20, 100, 371, 21))
        self.Sep1.setFrameShape(QtGui.QFrame.HLine)
        self.Sep1.setFrameShadow(QtGui.QFrame.Sunken)
        self.Sep1.setObjectName(_fromUtf8("Sep1"))
        self.LabelSyll = QtGui.QLabel(self.TabSpeciaux)
        self.LabelSyll.setGeometry(QtCore.QRect(50, 170, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelSyll.setFont(font)
        self.LabelSyll.setObjectName(_fromUtf8("LabelSyll"))
        self.RadioMotsFR = QtGui.QRadioButton(self.TabSpeciaux)
        self.RadioMotsFR.setGeometry(QtCore.QRect(20, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RadioMotsFR.setFont(font)
        self.RadioMotsFR.setChecked(True)
        self.RadioMotsFR.setObjectName(_fromUtf8("RadioMotsFR"))
        self.SBoxMotsFR = QtGui.QSpinBox(self.TabSpeciaux)
        self.SBoxMotsFR.setGeometry(QtCore.QRect(160, 20, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SBoxMotsFR.setFont(font)
        self.SBoxMotsFR.setAlignment(QtCore.Qt.AlignCenter)
        self.SBoxMotsFR.setMinimum(100)
        self.SBoxMotsFR.setMaximum(5000)
        self.SBoxMotsFR.setSingleStep(100)
        self.SBoxMotsFR.setProperty("value", 100)
        self.SBoxMotsFR.setObjectName(_fromUtf8("SBoxMotsFR"))
        self.LabelMotsFR1 = QtGui.QLabel(self.TabSpeciaux)
        self.LabelMotsFR1.setGeometry(QtCore.QRect(260, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelMotsFR1.setFont(font)
        self.LabelMotsFR1.setObjectName(_fromUtf8("LabelMotsFR1"))
        self.LabelMotsFR2 = QtGui.QLabel(self.TabSpeciaux)
        self.LabelMotsFR2.setGeometry(QtCore.QRect(50, 60, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelMotsFR2.setFont(font)
        self.LabelMotsFR2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LabelMotsFR2.setObjectName(_fromUtf8("LabelMotsFR2"))
        self.RadioSyll = QtGui.QRadioButton(self.TabSpeciaux)
        self.RadioSyll.setGeometry(QtCore.QRect(20, 130, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.RadioSyll.setFont(font)
        self.RadioSyll.setObjectName(_fromUtf8("RadioSyll"))
        self.EntrySyll = QtGui.QLineEdit(self.TabSpeciaux)
        self.EntrySyll.setGeometry(QtCore.QRect(240, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EntrySyll.setFont(font)
        self.EntrySyll.setMaxLength(5)
        self.EntrySyll.setAlignment(QtCore.Qt.AlignCenter)
        self.EntrySyll.setObjectName(_fromUtf8("EntrySyll"))
        self.TabSourceTexte.addTab(self.TabSpeciaux, _fromUtf8(""))
        self.TabExemple = QtGui.QWidget()
        self.TabExemple.setObjectName(_fromUtf8("TabExemple"))
        self.LabelTexteEx1R = QtGui.QRadioButton(self.TabExemple)
        self.LabelTexteEx1R.setGeometry(QtCore.QRect(20, 20, 371, 21))
        self.LabelTexteEx1R.setChecked(True)
        self.LabelTexteEx1R.setObjectName(_fromUtf8("LabelTexteEx1R"))
        self.LabelTexteEx2R = QtGui.QRadioButton(self.TabExemple)
        self.LabelTexteEx2R.setGeometry(QtCore.QRect(20, 80, 371, 21))
        self.LabelTexteEx2R.setObjectName(_fromUtf8("LabelTexteEx2R"))
        self.LabelTexteEx3R = QtGui.QRadioButton(self.TabExemple)
        self.LabelTexteEx3R.setGeometry(QtCore.QRect(20, 140, 371, 21))
        self.LabelTexteEx3R.setObjectName(_fromUtf8("LabelTexteEx3R"))
        self.LabelTexteEx1 = QtGui.QLabel(self.TabExemple)
        self.LabelTexteEx1.setGeometry(QtCore.QRect(20, 40, 371, 31))
        self.LabelTexteEx1.setObjectName(_fromUtf8("LabelTexteEx1"))
        self.LabelTexteEx2 = QtGui.QLabel(self.TabExemple)
        self.LabelTexteEx2.setGeometry(QtCore.QRect(20, 100, 371, 31))
        self.LabelTexteEx2.setObjectName(_fromUtf8("LabelTexteEx2"))
        self.LabelTexteEx3 = QtGui.QLabel(self.TabExemple)
        self.LabelTexteEx3.setGeometry(QtCore.QRect(20, 160, 371, 31))
        self.LabelTexteEx3.setObjectName(_fromUtf8("LabelTexteEx3"))
        self.TabSourceTexte.addTab(self.TabExemple, _fromUtf8(""))
        self.TabPerso = QtGui.QWidget()
        self.TabPerso.setObjectName(_fromUtf8("TabPerso"))
        self.CollerTexteR = QtGui.QRadioButton(self.TabPerso)
        self.CollerTexteR.setGeometry(QtCore.QRect(20, 10, 371, 21))
        self.CollerTexteR.setChecked(True)
        self.CollerTexteR.setObjectName(_fromUtf8("CollerTexteR"))
        self.CollerTexteV = QtGui.QPlainTextEdit(self.TabPerso)
        self.CollerTexteV.setGeometry(QtCore.QRect(20, 40, 371, 131))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CollerTexteV.setFont(font)
        self.CollerTexteV.setObjectName(_fromUtf8("CollerTexteV"))
        self.NomTexteR = QtGui.QRadioButton(self.TabPerso)
        self.NomTexteR.setGeometry(QtCore.QRect(20, 180, 151, 21))
        self.NomTexteR.setObjectName(_fromUtf8("NomTexteR"))
        self.NomTexteV = QtGui.QLineEdit(self.TabPerso)
        self.NomTexteV.setGeometry(QtCore.QRect(170, 180, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.NomTexteV.setFont(font)
        self.NomTexteV.setAlignment(QtCore.Qt.AlignCenter)
        self.NomTexteV.setObjectName(_fromUtf8("NomTexteV"))
        self.TabSourceTexte.addTab(self.TabPerso, _fromUtf8(""))
        self.FrameControles = QtGui.QFrame(self.ZoneCentrale)
        self.FrameControles.setGeometry(QtCore.QRect(510, 570, 451, 121))
        self.FrameControles.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrameControles.setFrameShadow(QtGui.QFrame.Raised)
        self.FrameControles.setObjectName(_fromUtf8("FrameControles"))
        self.LabelLancez = QtGui.QLabel(self.FrameControles)
        self.LabelLancez.setGeometry(QtCore.QRect(20, 20, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelLancez.setFont(font)
        self.LabelLancez.setObjectName(_fromUtf8("LabelLancez"))
        self.BoutonCommencer = QtGui.QPushButton(self.FrameControles)
        self.BoutonCommencer.setGeometry(QtCore.QRect(240, 50, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BoutonCommencer.setFont(font)
        self.BoutonCommencer.setObjectName(_fromUtf8("BoutonCommencer"))
        self.BoutonQuitter = QtGui.QPushButton(self.FrameControles)
        self.BoutonQuitter.setGeometry(QtCore.QRect(20, 50, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BoutonQuitter.setFont(font)
        self.BoutonQuitter.setObjectName(_fromUtf8("BoutonQuitter"))
        self.BoutonAide = QtGui.QPushButton(self.FrameControles)
        self.BoutonAide.setGeometry(QtCore.QRect(240, 20, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BoutonAide.setFont(font)
        self.BoutonAide.setObjectName(_fromUtf8("BoutonAide"))
        self.FramePseudo = QtGui.QFrame(self.ZoneCentrale)
        self.FramePseudo.setGeometry(QtCore.QRect(510, 470, 451, 91))
        self.FramePseudo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FramePseudo.setFrameShadow(QtGui.QFrame.Raised)
        self.FramePseudo.setObjectName(_fromUtf8("FramePseudo"))
        self.LabelPseudoT = QtGui.QLabel(self.FramePseudo)
        self.LabelPseudoT.setGeometry(QtCore.QRect(20, 20, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LabelPseudoT.setFont(font)
        self.LabelPseudoT.setObjectName(_fromUtf8("LabelPseudoT"))
        self.LabelPseudo = QtGui.QLabel(self.FramePseudo)
        self.LabelPseudo.setGeometry(QtCore.QRect(20, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelPseudo.setFont(font)
        self.LabelPseudo.setObjectName(_fromUtf8("LabelPseudo"))
        self.EntryPseudo = QtGui.QLineEdit(self.FramePseudo)
        self.EntryPseudo.setGeometry(QtCore.QRect(110, 50, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.EntryPseudo.setFont(font)
        self.EntryPseudo.setMaxLength(20)
        self.EntryPseudo.setAlignment(QtCore.Qt.AlignCenter)
        self.EntryPseudo.setObjectName(_fromUtf8("EntryPseudo"))
        self.LabelIcone = QtGui.QLabel(self.ZoneCentrale)
        self.LabelIcone.setGeometry(QtCore.QRect(40, 40, 921, 261))
        self.LabelIcone.setText(_fromUtf8(""))
        self.LabelIcone.setObjectName(_fromUtf8("LabelIcone"))
        Menu.setCentralWidget(self.ZoneCentrale)
        self.actionImprimer_scores = QtGui.QAction(Menu)
        self.actionImprimer_scores.setObjectName(_fromUtf8("actionImprimer_scores"))
        self.actionPoubelle_Ctrl_Q = QtGui.QAction(Menu)
        self.actionPoubelle_Ctrl_Q.setObjectName(_fromUtf8("actionPoubelle_Ctrl_Q"))
        self.actionPouet_OMFG = QtGui.QAction(Menu)
        self.actionPouet_OMFG.setObjectName(_fromUtf8("actionPouet_OMFG"))
        self.actionTruc_FTG = QtGui.QAction(Menu)
        self.actionTruc_FTG.setObjectName(_fromUtf8("actionTruc_FTG"))
        self.MenuFichierQuitter = QtGui.QAction(Menu)
        self.MenuFichierQuitter.setEnabled(True)
        self.MenuFichierQuitter.setObjectName(_fromUtf8("MenuFichierQuitter"))
        self.MenuFichierParDefaut = QtGui.QAction(Menu)
        self.MenuFichierParDefaut.setObjectName(_fromUtf8("MenuFichierParDefaut"))
        self.MenuAideOuvrirAide = QtGui.QAction(Menu)
        self.MenuAideOuvrirAide.setObjectName(_fromUtf8("MenuAideOuvrirAide"))
        self.MenuAideOuvrirCredits = QtGui.QAction(Menu)
        self.MenuAideOuvrirCredits.setObjectName(_fromUtf8("MenuAideOuvrirCredits"))

        self.retranslateUi(Menu)
        self.TabSourceTexte.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        Menu.setWindowTitle(_translate("Menu", "Menu", None))
        self.LabelChoisissez.setText(_translate("Menu", "Choisissez vos options !", None))
        self.LabelTempsJeuT.setText(_translate("Menu", "2. Choisissez votre temps de jeu", None))
        self.LabelTempsJeuMinutes.setText(_translate("Menu", "Minutes", None))
        self.LabelTempsJeuSecondes.setText(_translate("Menu", "Secondes", None))
        self.LabelTempsColon.setText(_translate("Menu", ":", None))
        self.LabelSource.setText(_translate("Menu", "1. Choisissez votre source de texte", None))
        self.LabelSyll.setText(_translate("Menu", "possédant la syllabe", None))
        self.RadioMotsFR.setText(_translate("Menu", " Affiche&r les", None))
        self.LabelMotsFR1.setText(_translate("Menu", "mots les plus", None))
        self.LabelMotsFR2.setText(_translate("Menu", "utilisés de la langue française", None))
        self.RadioSyll.setText(_translate("Menu", " Afficher uni&quement des mots", None))
        self.TabSourceTexte.setTabText(self.TabSourceTexte.indexOf(self.TabSpeciaux), _translate("Menu", "Mots spéciaux", None))
        self.LabelTexteEx1R.setText(_translate("Menu", "Tchoupi va &à la plage", None))
        self.LabelTexteEx2R.setText(_translate("Menu", "Tchoupi &va à la boulangerie", None))
        self.LabelTexteEx3R.setText(_translate("Menu", "Tchoupi va au &bordel", None))
        self.LabelTexteEx1.setText(_translate("Menu", "Difficulté *", None))
        self.LabelTexteEx2.setText(_translate("Menu", "Difficulté **", None))
        self.LabelTexteEx3.setText(_translate("Menu", "Difficulté ***", None))
        self.TabSourceTexte.setTabText(self.TabSourceTexte.indexOf(self.TabExemple), _translate("Menu", "Exemple de texte", None))
        self.CollerTexteR.setText(_translate("Menu", "&Texte (copier-coller) :", None))
        self.NomTexteR.setText(_translate("Menu", "Nom du fichier :", None))
        self.TabSourceTexte.setTabText(self.TabSourceTexte.indexOf(self.TabPerso), _translate("Menu", "Texte personnel", None))
        self.LabelLancez.setText(_translate("Menu", "4. Lancez-vous !", None))
        self.BoutonCommencer.setText(_translate("Menu", "Commencer", None))
        self.BoutonQuitter.setText(_translate("Menu", "Quitter", None))
        self.BoutonAide.setText(_translate("Menu", "Aide et Crédits", None))
        self.LabelPseudoT.setText(_translate("Menu", "3. Choisissez votre pseudo (facultatif)", None))
        self.LabelPseudo.setText(_translate("Menu", "Pseudo :", None))
        self.actionImprimer_scores.setText(_translate("Menu", "Imprimer scores", None))
        self.actionPoubelle_Ctrl_Q.setText(_translate("Menu", "Poubelle (Ctrl + Q)", None))
        self.actionPouet_OMFG.setText(_translate("Menu", "Pouet (OMFG)", None))
        self.actionTruc_FTG.setText(_translate("Menu", "Truc (FTG)", None))
        self.MenuFichierQuitter.setText(_translate("Menu", "&Quitter (Ctrl + Q)", None))
        self.MenuFichierParDefaut.setText(_translate("Menu", "&Par Défaut (Ctrl + D)", None))
        self.MenuAideOuvrirAide.setText(_translate("Menu", "&Ouvrir le fichier d\'aide (Ctrl + H)", None))
        self.MenuAideOuvrirCredits.setText(_translate("Menu", "Ouvrir &les crédits (Ctrl + R)", None))

