# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/Menu/menu.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName(_fromUtf8("Menu"))
        Menu.resize(1000, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Menu.sizePolicy().hasHeightForWidth())
        Menu.setSizePolicy(sizePolicy)
        Menu.setMinimumSize(QtCore.QSize(1000, 600))
        Menu.setMaximumSize(QtCore.QSize(1000, 600))
        self.ZoneCentrale = QtGui.QWidget(Menu)
        self.ZoneCentrale.setObjectName(_fromUtf8("ZoneCentrale"))
        self.LabelIcone = QtGui.QGraphicsView(self.ZoneCentrale)
        self.LabelIcone.setGeometry(QtCore.QRect(40, 40, 921, 101))
        self.LabelIcone.setObjectName(_fromUtf8("LabelIcone"))
        self.LabelChoisissez = QtGui.QLabel(self.ZoneCentrale)
        self.LabelChoisissez.setGeometry(QtCore.QRect(280, 160, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LabelChoisissez.setFont(font)
        self.LabelChoisissez.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelChoisissez.setObjectName(_fromUtf8("LabelChoisissez"))
        self.FrameModeJeu = QtGui.QFrame(self.ZoneCentrale)
        self.FrameModeJeu.setGeometry(QtCore.QRect(40, 210, 451, 151))
        self.FrameModeJeu.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrameModeJeu.setFrameShadow(QtGui.QFrame.Plain)
        self.FrameModeJeu.setObjectName(_fromUtf8("FrameModeJeu"))
        self.LabelMode = QtGui.QLabel(self.FrameModeJeu)
        self.LabelMode.setGeometry(QtCore.QRect(20, 20, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelMode.setFont(font)
        self.LabelMode.setObjectName(_fromUtf8("LabelMode"))
        self.TabMode = QtGui.QTabWidget(self.FrameModeJeu)
        self.TabMode.setGeometry(QtCore.QRect(20, 50, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TabMode.setFont(font)
        self.TabMode.setTabShape(QtGui.QTabWidget.Rounded)
        self.TabMode.setDocumentMode(False)
        self.TabMode.setTabsClosable(False)
        self.TabMode.setMovable(False)
        self.TabMode.setObjectName(_fromUtf8("TabMode"))
        self.TabTempsLimite = QtGui.QWidget()
        self.TabTempsLimite.setObjectName(_fromUtf8("TabTempsLimite"))
        self.LabelTempsLimite = QtGui.QLabel(self.TabTempsLimite)
        self.LabelTempsLimite.setGeometry(QtCore.QRect(10, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelTempsLimite.setFont(font)
        self.LabelTempsLimite.setObjectName(_fromUtf8("LabelTempsLimite"))
        self.EntryTempsLimite = QtGui.QLineEdit(self.TabTempsLimite)
        self.EntryTempsLimite.setGeometry(QtCore.QRect(240, 10, 151, 31))
        self.EntryTempsLimite.setObjectName(_fromUtf8("EntryTempsLimite"))
        self.TabMode.addTab(self.TabTempsLimite, _fromUtf8(""))
        self.TabMotLimite = QtGui.QWidget()
        self.TabMotLimite.setObjectName(_fromUtf8("TabMotLimite"))
        self.LabelMotLimite = QtGui.QLabel(self.TabMotLimite)
        self.LabelMotLimite.setGeometry(QtCore.QRect(10, 10, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelMotLimite.setFont(font)
        self.LabelMotLimite.setObjectName(_fromUtf8("LabelMotLimite"))
        self.EntryMotLimite = QtGui.QLineEdit(self.TabMotLimite)
        self.EntryMotLimite.setGeometry(QtCore.QRect(240, 10, 151, 31))
        self.EntryMotLimite.setObjectName(_fromUtf8("EntryMotLimite"))
        self.TabMode.addTab(self.TabMotLimite, _fromUtf8(""))
        self.FrameModeCorrection = QtGui.QFrame(self.ZoneCentrale)
        self.FrameModeCorrection.setGeometry(QtCore.QRect(40, 380, 451, 151))
        self.FrameModeCorrection.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrameModeCorrection.setFrameShadow(QtGui.QFrame.Raised)
        self.FrameModeCorrection.setObjectName(_fromUtf8("FrameModeCorrection"))
        self.LabelCorrection = QtGui.QLabel(self.FrameModeCorrection)
        self.LabelCorrection.setGeometry(QtCore.QRect(20, 20, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelCorrection.setFont(font)
        self.LabelCorrection.setObjectName(_fromUtf8("LabelCorrection"))
        self.CorrManuValJuste = QtGui.QRadioButton(self.FrameModeCorrection)
        self.CorrManuValJuste.setGeometry(QtCore.QRect(10, 50, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CorrManuValJuste.setFont(font)
        self.CorrManuValJuste.setObjectName(_fromUtf8("CorrManuValJuste"))
        self.CorrManuValAll = QtGui.QRadioButton(self.FrameModeCorrection)
        self.CorrManuValAll.setGeometry(QtCore.QRect(10, 80, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CorrManuValAll.setFont(font)
        self.CorrManuValAll.setObjectName(_fromUtf8("CorrManuValAll"))
        self.CorrAuto = QtGui.QRadioButton(self.FrameModeCorrection)
        self.CorrAuto.setGeometry(QtCore.QRect(10, 110, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CorrAuto.setFont(font)
        self.CorrAuto.setObjectName(_fromUtf8("CorrAuto"))
        self.FrameSource = QtGui.QFrame(self.ZoneCentrale)
        self.FrameSource.setGeometry(QtCore.QRect(510, 210, 451, 151))
        self.FrameSource.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrameSource.setFrameShadow(QtGui.QFrame.Raised)
        self.FrameSource.setObjectName(_fromUtf8("FrameSource"))
        self.LabelSource = QtGui.QLabel(self.FrameSource)
        self.LabelSource.setGeometry(QtCore.QRect(20, 20, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelSource.setFont(font)
        self.LabelSource.setObjectName(_fromUtf8("LabelSource"))
        self.TabSource = QtGui.QTabWidget(self.FrameSource)
        self.TabSource.setGeometry(QtCore.QRect(20, 50, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TabSource.setFont(font)
        self.TabSource.setObjectName(_fromUtf8("TabSource"))
        self.TabMotsFR = QtGui.QWidget()
        self.TabMotsFR.setObjectName(_fromUtf8("TabMotsFR"))
        self.LabelMotsFR = QtGui.QLabel(self.TabMotsFR)
        self.LabelMotsFR.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.LabelMotsFR.setWordWrap(True)
        self.LabelMotsFR.setObjectName(_fromUtf8("LabelMotsFR"))
        self.EntryMotsFR = QtGui.QLineEdit(self.TabMotsFR)
        self.EntryMotsFR.setGeometry(QtCore.QRect(160, 10, 231, 31))
        self.EntryMotsFR.setObjectName(_fromUtf8("EntryMotsFR"))
        self.TabSource.addTab(self.TabMotsFR, _fromUtf8(""))
        self.TabActu = QtGui.QWidget()
        self.TabActu.setObjectName(_fromUtf8("TabActu"))
        self.EntryActu = QtGui.QLineEdit(self.TabActu)
        self.EntryActu.setGeometry(QtCore.QRect(160, 10, 231, 31))
        self.EntryActu.setObjectName(_fromUtf8("EntryActu"))
        self.LabelActu = QtGui.QLabel(self.TabActu)
        self.LabelActu.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.LabelActu.setWordWrap(True)
        self.LabelActu.setObjectName(_fromUtf8("LabelActu"))
        self.TabSource.addTab(self.TabActu, _fromUtf8(""))
        self.TabPerso = QtGui.QWidget()
        self.TabPerso.setObjectName(_fromUtf8("TabPerso"))
        self.LabelPerso = QtGui.QLabel(self.TabPerso)
        self.LabelPerso.setGeometry(QtCore.QRect(10, 10, 151, 31))
        self.LabelPerso.setWordWrap(True)
        self.LabelPerso.setObjectName(_fromUtf8("LabelPerso"))
        self.EntryPerso = QtGui.QTextEdit(self.TabPerso)
        self.EntryPerso.setGeometry(QtCore.QRect(160, 10, 231, 31))
        self.EntryPerso.setObjectName(_fromUtf8("EntryPerso"))
        self.TabSource.addTab(self.TabPerso, _fromUtf8(""))
        self.FrameControles = QtGui.QFrame(self.ZoneCentrale)
        self.FrameControles.setGeometry(QtCore.QRect(510, 380, 451, 151))
        self.FrameControles.setFrameShape(QtGui.QFrame.StyledPanel)
        self.FrameControles.setFrameShadow(QtGui.QFrame.Raised)
        self.FrameControles.setObjectName(_fromUtf8("FrameControles"))
        self.LabelLancez = QtGui.QLabel(self.FrameControles)
        self.LabelLancez.setGeometry(QtCore.QRect(20, 20, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelLancez.setFont(font)
        self.LabelLancez.setObjectName(_fromUtf8("LabelLancez"))
        self.BoutonCommencer = QtGui.QPushButton(self.FrameControles)
        self.BoutonCommencer.setGeometry(QtCore.QRect(240, 70, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BoutonCommencer.setFont(font)
        self.BoutonCommencer.setObjectName(_fromUtf8("BoutonCommencer"))
        self.BoutonQuitter = QtGui.QPushButton(self.FrameControles)
        self.BoutonQuitter.setGeometry(QtCore.QRect(20, 70, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BoutonQuitter.setFont(font)
        self.BoutonQuitter.setObjectName(_fromUtf8("BoutonQuitter"))
        self.BoutonAide = QtGui.QPushButton(self.FrameControles)
        self.BoutonAide.setGeometry(QtCore.QRect(240, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BoutonAide.setFont(font)
        self.BoutonAide.setObjectName(_fromUtf8("BoutonAide"))
        self.EntryParam = QtGui.QLineEdit(self.ZoneCentrale)
        self.EntryParam.setGeometry(QtCore.QRect(40, 540, 741, 21))
        self.EntryParam.setObjectName(_fromUtf8("EntryParam"))
        self.BoutonGenererParam = QtGui.QPushButton(self.ZoneCentrale)
        self.BoutonGenererParam.setGeometry(QtCore.QRect(790, 540, 81, 21))
        self.BoutonGenererParam.setObjectName(_fromUtf8("BoutonGenererParam"))
        self.BoutonAppliquerParam = QtGui.QPushButton(self.ZoneCentrale)
        self.BoutonAppliquerParam.setGeometry(QtCore.QRect(880, 540, 81, 21))
        self.BoutonAppliquerParam.setObjectName(_fromUtf8("BoutonAppliquerParam"))
        Menu.setCentralWidget(self.ZoneCentrale)
        self.BarreMenu = QtGui.QMenuBar(Menu)
        self.BarreMenu.setGeometry(QtCore.QRect(0, 0, 1000, 20))
        self.BarreMenu.setObjectName(_fromUtf8("BarreMenu"))
        self.MenuFichier = QtGui.QMenu(self.BarreMenu)
        self.MenuFichier.setObjectName(_fromUtf8("MenuFichier"))
        self.MenuAide = QtGui.QMenu(self.BarreMenu)
        self.MenuAide.setObjectName(_fromUtf8("MenuAide"))
        Menu.setMenuBar(self.BarreMenu)
        self.actionImprimer_scores = QtGui.QAction(Menu)
        self.actionImprimer_scores.setObjectName(_fromUtf8("actionImprimer_scores"))
        self.actionPoubelle_Ctrl_Q = QtGui.QAction(Menu)
        self.actionPoubelle_Ctrl_Q.setObjectName(_fromUtf8("actionPoubelle_Ctrl_Q"))
        self.actionPouet_OMFG = QtGui.QAction(Menu)
        self.actionPouet_OMFG.setObjectName(_fromUtf8("actionPouet_OMFG"))
        self.actionTruc_FTG = QtGui.QAction(Menu)
        self.actionTruc_FTG.setObjectName(_fromUtf8("actionTruc_FTG"))
        self.MenuFichierQuitter = QtGui.QAction(Menu)
        self.MenuFichierQuitter.setObjectName(_fromUtf8("MenuFichierQuitter"))
        self.MenuFichierParDefaut = QtGui.QAction(Menu)
        self.MenuFichierParDefaut.setObjectName(_fromUtf8("MenuFichierParDefaut"))
        self.MenuAideOuvrirAide = QtGui.QAction(Menu)
        self.MenuAideOuvrirAide.setObjectName(_fromUtf8("MenuAideOuvrirAide"))
        self.MenuAideOuvrirCredits = QtGui.QAction(Menu)
        self.MenuAideOuvrirCredits.setObjectName(_fromUtf8("MenuAideOuvrirCredits"))
        self.MenuFichier.addAction(self.MenuFichierQuitter)
        self.MenuFichier.addAction(self.MenuFichierParDefaut)
        self.MenuAide.addAction(self.MenuAideOuvrirAide)
        self.MenuAide.addAction(self.MenuAideOuvrirCredits)
        self.BarreMenu.addAction(self.MenuFichier.menuAction())
        self.BarreMenu.addAction(self.MenuAide.menuAction())

        self.retranslateUi(Menu)
        self.TabMode.setCurrentIndex(1)
        self.TabSource.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        Menu.setWindowTitle(_translate("Menu", "Menu", None))
        self.LabelChoisissez.setText(_translate("Menu", "Choisissez vos options !", None))
        self.LabelMode.setText(_translate("Menu", "1. Choisissez votre mode de jeu", None))
        self.LabelTempsLimite.setText(_translate("Menu", "Temps (secondes) :", None))
        self.TabMode.setTabText(self.TabMode.indexOf(self.TabTempsLimite), _translate("Menu", "Temps limité", None))
        self.LabelMotLimite.setText(_translate("Menu", "Nombre de mots :", None))
        self.TabMode.setTabText(self.TabMode.indexOf(self.TabMotLimite), _translate("Menu", "Nombre de mots limité", None))
        self.LabelCorrection.setText(_translate("Menu", "2. Choisissez votre mode de correction", None))
        self.CorrManuValJuste.setText(_translate("Menu", "Correction avec <--- Validation &quand le mot est juste", None))
        self.CorrManuValAll.setText(_translate("Menu", "Correction avec <--- &Validation dans tous les cas", None))
        self.CorrAuto.setText(_translate("Menu", "Co&rrection automatique", None))
        self.LabelSource.setText(_translate("Menu", "3. Choisissez votre source de texte", None))
        self.LabelMotsFR.setText(_translate("Menu", "Nombre de mots les plus utilisés :", None))
        self.TabSource.setTabText(self.TabSource.indexOf(self.TabMotsFR), _translate("Menu", "Mots les plus utilisés", None))
        self.LabelActu.setText(_translate("Menu", "Nombre de lignes :", None))
        self.TabSource.setTabText(self.TabSource.indexOf(self.TabActu), _translate("Menu", "Texte d\'actu", None))
        self.LabelPerso.setText(_translate("Menu", "Lien ou copier-coller du texte :", None))
        self.TabSource.setTabText(self.TabSource.indexOf(self.TabPerso), _translate("Menu", "Texte perso", None))
        self.LabelLancez.setText(_translate("Menu", "4. Lancez-vous !", None))
        self.BoutonCommencer.setText(_translate("Menu", "Commencer", None))
        self.BoutonQuitter.setText(_translate("Menu", "Quitter", None))
        self.BoutonAide.setText(_translate("Menu", "Aide et Crédits", None))
        self.BoutonGenererParam.setText(_translate("Menu", "Générer", None))
        self.BoutonAppliquerParam.setText(_translate("Menu", "Appliquer", None))
        self.MenuFichier.setTitle(_translate("Menu", "Fic&hier", None))
        self.MenuAide.setTitle(_translate("Menu", "Aide", None))
        self.actionImprimer_scores.setText(_translate("Menu", "Imprimer scores", None))
        self.actionPoubelle_Ctrl_Q.setText(_translate("Menu", "Poubelle (Ctrl + Q)", None))
        self.actionPouet_OMFG.setText(_translate("Menu", "Pouet (OMFG)", None))
        self.actionTruc_FTG.setText(_translate("Menu", "Truc (FTG)", None))
        self.MenuFichierQuitter.setText(_translate("Menu", "&Quitter (Ctrl + Q)", None))
        self.MenuFichierParDefaut.setText(_translate("Menu", "&Par Défaut (Ctrl + D)", None))
        self.MenuAideOuvrirAide.setText(_translate("Menu", "&Ouvrir le fichier d\'aide (Ctrl + H)", None))
        self.MenuAideOuvrirCredits.setText(_translate("Menu", "Ouvrir &les crédits (Ctrl + R)", None))

