# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/Module/module.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Module(object):
    def setupUi(self, Module):
        Module.setObjectName(_fromUtf8("Module"))
        Module.resize(1200, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Module.sizePolicy().hasHeightForWidth())
        Module.setSizePolicy(sizePolicy)
        Module.setMinimumSize(QtCore.QSize(1200, 600))
        Module.setMaximumSize(QtCore.QSize(1200, 600))
        self.Fenetre = QtGui.QWidget(Module)
        self.Fenetre.setObjectName(_fromUtf8("Fenetre"))
        self.SFrameAvancement = QtGui.QFrame(self.Fenetre)
        self.SFrameAvancement.setGeometry(QtCore.QRect(20, 150, 281, 411))
        self.SFrameAvancement.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SFrameAvancement.setFrameShadow(QtGui.QFrame.Raised)
        self.SFrameAvancement.setObjectName(_fromUtf8("SFrameAvancement"))
        self.LabelAvancementT = QtGui.QLabel(self.SFrameAvancement)
        self.LabelAvancementT.setGeometry(QtCore.QRect(20, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelAvancementT.setFont(font)
        self.LabelAvancementT.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelAvancementT.setObjectName(_fromUtf8("LabelAvancementT"))
        self.BarreAvancement = QtGui.QProgressBar(self.SFrameAvancement)
        self.BarreAvancement.setGeometry(QtCore.QRect(20, 50, 111, 341))
        self.BarreAvancement.setProperty("value", 68)
        self.BarreAvancement.setTextVisible(False)
        self.BarreAvancement.setOrientation(QtCore.Qt.Vertical)
        self.BarreAvancement.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.BarreAvancement.setObjectName(_fromUtf8("BarreAvancement"))
        self.Label100 = QtGui.QLabel(self.SFrameAvancement)
        self.Label100.setGeometry(QtCore.QRect(210, 30, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label100.setFont(font)
        self.Label100.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Label100.setObjectName(_fromUtf8("Label100"))
        self.Label50 = QtGui.QLabel(self.SFrameAvancement)
        self.Label50.setGeometry(QtCore.QRect(210, 200, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label50.setFont(font)
        self.Label50.setObjectName(_fromUtf8("Label50"))
        self.Label0 = QtGui.QLabel(self.SFrameAvancement)
        self.Label0.setGeometry(QtCore.QRect(210, 370, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label0.setFont(font)
        self.Label0.setObjectName(_fromUtf8("Label0"))
        self.Ligne100 = QtGui.QFrame(self.SFrameAvancement)
        self.Ligne100.setGeometry(QtCore.QRect(140, 35, 61, 31))
        self.Ligne100.setFrameShape(QtGui.QFrame.HLine)
        self.Ligne100.setFrameShadow(QtGui.QFrame.Sunken)
        self.Ligne100.setObjectName(_fromUtf8("Ligne100"))
        self.Ligne50 = QtGui.QFrame(self.SFrameAvancement)
        self.Ligne50.setGeometry(QtCore.QRect(140, 210, 61, 21))
        self.Ligne50.setFrameShape(QtGui.QFrame.HLine)
        self.Ligne50.setFrameShadow(QtGui.QFrame.Sunken)
        self.Ligne50.setObjectName(_fromUtf8("Ligne50"))
        self.Ligne0 = QtGui.QFrame(self.SFrameAvancement)
        self.Ligne0.setGeometry(QtCore.QRect(140, 380, 61, 21))
        self.Ligne0.setFrameShape(QtGui.QFrame.HLine)
        self.Ligne0.setFrameShadow(QtGui.QFrame.Sunken)
        self.Ligne0.setObjectName(_fromUtf8("Ligne0"))
        self.SFrameTemps = QtGui.QFrame(self.Fenetre)
        self.SFrameTemps.setGeometry(QtCore.QRect(900, 150, 281, 411))
        self.SFrameTemps.setAutoFillBackground(False)
        self.SFrameTemps.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SFrameTemps.setFrameShadow(QtGui.QFrame.Raised)
        self.SFrameTemps.setObjectName(_fromUtf8("SFrameTemps"))
        self.LabelRestantT = QtGui.QLabel(self.SFrameTemps)
        self.LabelRestantT.setGeometry(QtCore.QRect(10, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelRestantT.setFont(font)
        self.LabelRestantT.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelRestantT.setObjectName(_fromUtf8("LabelRestantT"))
        self.LabelRestantV = QtGui.QLabel(self.SFrameTemps)
        self.LabelRestantV.setGeometry(QtCore.QRect(10, 50, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.LabelRestantV.setFont(font)
        self.LabelRestantV.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LabelRestantV.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelRestantV.setObjectName(_fromUtf8("LabelRestantV"))
        self.LabelSMots = QtGui.QLabel(self.SFrameTemps)
        self.LabelSMots.setGeometry(QtCore.QRect(190, 200, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelSMots.setFont(font)
        self.LabelSMots.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelSMots.setObjectName(_fromUtf8("LabelSMots"))
        self.LigneRestant2Scores = QtGui.QFrame(self.SFrameTemps)
        self.LigneRestant2Scores.setGeometry(QtCore.QRect(10, 140, 261, 16))
        self.LigneRestant2Scores.setFrameShape(QtGui.QFrame.HLine)
        self.LigneRestant2Scores.setFrameShadow(QtGui.QFrame.Sunken)
        self.LigneRestant2Scores.setObjectName(_fromUtf8("LigneRestant2Scores"))
        self.LabelSMotsV = QtGui.QLabel(self.SFrameTemps)
        self.LabelSMotsV.setGeometry(QtCore.QRect(20, 200, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LabelSMotsV.setFont(font)
        self.LabelSMotsV.setObjectName(_fromUtf8("LabelSMotsV"))
        self.LabelScore = QtGui.QLabel(self.SFrameTemps)
        self.LabelScore.setGeometry(QtCore.QRect(190, 230, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelScore.setFont(font)
        self.LabelScore.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelScore.setObjectName(_fromUtf8("LabelScore"))
        self.LabelScoreV = QtGui.QLabel(self.SFrameTemps)
        self.LabelScoreV.setGeometry(QtCore.QRect(20, 230, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LabelScoreV.setFont(font)
        self.LabelScoreV.setObjectName(_fromUtf8("LabelScoreV"))
        self.LigneScores2Best = QtGui.QFrame(self.SFrameTemps)
        self.LigneScores2Best.setGeometry(QtCore.QRect(10, 260, 261, 20))
        self.LigneScores2Best.setFrameShape(QtGui.QFrame.HLine)
        self.LigneScores2Best.setFrameShadow(QtGui.QFrame.Sunken)
        self.LigneScores2Best.setObjectName(_fromUtf8("LigneScores2Best"))
        self.ScoresBox = QtGui.QScrollArea(self.SFrameTemps)
        self.ScoresBox.setGeometry(QtCore.QRect(10, 310, 261, 91))
        self.ScoresBox.setWidgetResizable(True)
        self.ScoresBox.setObjectName(_fromUtf8("ScoresBox"))
        self.SScoresBox = QtGui.QWidget()
        self.SScoresBox.setGeometry(QtCore.QRect(0, 0, 259, 89))
        self.SScoresBox.setObjectName(_fromUtf8("SScoresBox"))
        self.ScoresBox.setWidget(self.SScoresBox)
        self.LabelScoreT = QtGui.QLabel(self.SFrameTemps)
        self.LabelScoreT.setGeometry(QtCore.QRect(10, 160, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelScoreT.setFont(font)
        self.LabelScoreT.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelScoreT.setObjectName(_fromUtf8("LabelScoreT"))
        self.LabelBestT = QtGui.QLabel(self.SFrameTemps)
        self.LabelBestT.setGeometry(QtCore.QRect(10, 280, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelBestT.setFont(font)
        self.LabelBestT.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelBestT.setObjectName(_fromUtf8("LabelBestT"))
        self.SFrame1Saisie = QtGui.QGraphicsView(self.Fenetre)
        self.SFrame1Saisie.setGeometry(QtCore.QRect(20, 20, 1161, 111))
        self.SFrame1Saisie.setFrameShape(QtGui.QFrame.NoFrame)
        self.SFrame1Saisie.setObjectName(_fromUtf8("SFrame1Saisie"))
        self.SFrameControle = QtGui.QFrame(self.Fenetre)
        self.SFrameControle.setGeometry(QtCore.QRect(320, 440, 561, 121))
        self.SFrameControle.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SFrameControle.setFrameShadow(QtGui.QFrame.Raised)
        self.SFrameControle.setObjectName(_fromUtf8("SFrameControle"))
        self.BoutonStartPause = QtGui.QPushButton(self.SFrameControle)
        self.BoutonStartPause.setGeometry(QtCore.QRect(10, 60, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BoutonStartPause.setFont(font)
        self.BoutonStartPause.setObjectName(_fromUtf8("BoutonStartPause"))
        self.BoutonQuitter = QtGui.QPushButton(self.SFrameControle)
        self.BoutonQuitter.setGeometry(QtCore.QRect(290, 60, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BoutonQuitter.setFont(font)
        self.BoutonQuitter.setObjectName(_fromUtf8("BoutonQuitter"))
        self.LabelInfo = QtGui.QLabel(self.SFrameControle)
        self.LabelInfo.setGeometry(QtCore.QRect(10, 10, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LabelInfo.setFont(font)
        self.LabelInfo.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LabelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelInfo.setObjectName(_fromUtf8("LabelInfo"))
        self.LabelTexteDroite = QtGui.QLabel(self.Fenetre)
        self.LabelTexteDroite.setGeometry(QtCore.QRect(50, 50, 531, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(30)
        self.LabelTexteDroite.setFont(font)
        self.LabelTexteDroite.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LabelTexteDroite.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelTexteDroite.setIndent(0)
        self.LabelTexteDroite.setObjectName(_fromUtf8("LabelTexteDroite"))
        self.LabelTexteGauche = QtGui.QLabel(self.Fenetre)
        self.LabelTexteGauche.setGeometry(QtCore.QRect(620, 50, 531, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(30)
        self.LabelTexteGauche.setFont(font)
        self.LabelTexteGauche.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LabelTexteGauche.setIndent(0)
        self.LabelTexteGauche.setObjectName(_fromUtf8("LabelTexteGauche"))
        self.LabelTexteCentre = QtGui.QLabel(self.Fenetre)
        self.LabelTexteCentre.setGeometry(QtCore.QRect(580, 50, 41, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(30)
        self.LabelTexteCentre.setFont(font)
        self.LabelTexteCentre.setFrameShape(QtGui.QFrame.WinPanel)
        self.LabelTexteCentre.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelTexteCentre.setObjectName(_fromUtf8("LabelTexteCentre"))
        self.SFrame2Saisie = QtGui.QGraphicsView(self.Fenetre)
        self.SFrame2Saisie.setGeometry(QtCore.QRect(320, 130, 561, 81))
        self.SFrame2Saisie.setFrameShape(QtGui.QFrame.NoFrame)
        self.SFrame2Saisie.setObjectName(_fromUtf8("SFrame2Saisie"))
        self.EntryTapeCentre = QtGui.QLineEdit(self.Fenetre)
        self.EntryTapeCentre.setGeometry(QtCore.QRect(580, 130, 41, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(30)
        self.EntryTapeCentre.setFont(font)
        self.EntryTapeCentre.setText(_fromUtf8(""))
        self.EntryTapeCentre.setAlignment(QtCore.Qt.AlignCenter)
        self.EntryTapeCentre.setObjectName(_fromUtf8("EntryTapeCentre"))
        self.LabelTapeDroit = QtGui.QLabel(self.Fenetre)
        self.LabelTapeDroit.setGeometry(QtCore.QRect(350, 130, 231, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(30)
        self.LabelTapeDroit.setFont(font)
        self.LabelTapeDroit.setFrameShape(QtGui.QFrame.StyledPanel)
        self.LabelTapeDroit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabelTapeDroit.setIndent(0)
        self.LabelTapeDroit.setObjectName(_fromUtf8("LabelTapeDroit"))
        self.LabelTapeFleche = QtGui.QLabel(self.Fenetre)
        self.LabelTapeFleche.setGeometry(QtCore.QRect(620, 130, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.LabelTapeFleche.setFont(font)
        self.LabelTapeFleche.setFrameShape(QtGui.QFrame.NoFrame)
        self.LabelTapeFleche.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelTapeFleche.setIndent(0)
        self.LabelTapeFleche.setObjectName(_fromUtf8("LabelTapeFleche"))
        self.SFenetreStat = QtGui.QFrame(self.Fenetre)
        self.SFenetreStat.setGeometry(QtCore.QRect(320, 290, 561, 131))
        self.SFenetreStat.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SFenetreStat.setFrameShadow(QtGui.QFrame.Raised)
        self.SFenetreStat.setObjectName(_fromUtf8("SFenetreStat"))
        self.LabelStatT = QtGui.QLabel(self.SFenetreStat)
        self.LabelStatT.setGeometry(QtCore.QRect(160, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelStatT.setFont(font)
        self.LabelStatT.setAlignment(QtCore.Qt.AlignCenter)
        self.LabelStatT.setObjectName(_fromUtf8("LabelStatT"))
        self.BarreReussite = QtGui.QProgressBar(self.SFenetreStat)
        self.BarreReussite.setGeometry(QtCore.QRect(20, 40, 411, 31))
        self.BarreReussite.setAutoFillBackground(True)
        self.BarreReussite.setProperty("value", 75)
        self.BarreReussite.setTextVisible(False)
        self.BarreReussite.setInvertedAppearance(False)
        self.BarreReussite.setObjectName(_fromUtf8("BarreReussite"))
        self.BarreErreurs = QtGui.QProgressBar(self.SFenetreStat)
        self.BarreErreurs.setGeometry(QtCore.QRect(20, 80, 411, 31))
        self.BarreErreurs.setAutoFillBackground(True)
        self.BarreErreurs.setProperty("value", 25)
        self.BarreErreurs.setTextVisible(False)
        self.BarreErreurs.setInvertedAppearance(True)
        self.BarreErreurs.setObjectName(_fromUtf8("BarreErreurs"))
        self.LabelReussite = QtGui.QLabel(self.SFenetreStat)
        self.LabelReussite.setGeometry(QtCore.QRect(450, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelReussite.setFont(font)
        self.LabelReussite.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LabelReussite.setObjectName(_fromUtf8("LabelReussite"))
        self.LabelErreurs = QtGui.QLabel(self.SFenetreStat)
        self.LabelErreurs.setGeometry(QtCore.QRect(450, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LabelErreurs.setFont(font)
        self.LabelErreurs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LabelErreurs.setObjectName(_fromUtf8("LabelErreurs"))
        self.SFenetreEtoiles = QtGui.QFrame(self.Fenetre)
        self.SFenetreEtoiles.setGeometry(QtCore.QRect(320, 230, 561, 41))
        self.SFenetreEtoiles.setFrameShape(QtGui.QFrame.StyledPanel)
        self.SFenetreEtoiles.setFrameShadow(QtGui.QFrame.Raised)
        self.SFenetreEtoiles.setObjectName(_fromUtf8("SFenetreEtoiles"))
        self.Etoile1 = QtGui.QGraphicsView(self.SFenetreEtoiles)
        self.Etoile1.setGeometry(QtCore.QRect(0, 0, 187, 41))
        self.Etoile1.setObjectName(_fromUtf8("Etoile1"))
        self.Etoile2 = QtGui.QGraphicsView(self.SFenetreEtoiles)
        self.Etoile2.setGeometry(QtCore.QRect(187, 0, 187, 41))
        self.Etoile2.setObjectName(_fromUtf8("Etoile2"))
        self.Etoile3 = QtGui.QGraphicsView(self.SFenetreEtoiles)
        self.Etoile3.setGeometry(QtCore.QRect(374, 0, 187, 41))
        self.Etoile3.setObjectName(_fromUtf8("Etoile3"))
        Module.setCentralWidget(self.Fenetre)
        self.Menu = QtGui.QMenuBar(Module)
        self.Menu.setGeometry(QtCore.QRect(0, 0, 1200, 20))
        self.Menu.setObjectName(_fromUtf8("Menu"))
        Module.setMenuBar(self.Menu)

        self.retranslateUi(Module)
        QtCore.QObject.connect(self.BoutonQuitter, QtCore.SIGNAL(_fromUtf8("clicked()")), Module.close)
        QtCore.QMetaObject.connectSlotsByName(Module)

    def retranslateUi(self, Module):
        Module.setWindowTitle(_translate("Module", "Module", None))
        self.LabelAvancementT.setText(_translate("Module", "Avancement", None))
        self.Label100.setText(_translate("Module", "100 %", None))
        self.Label50.setText(_translate("Module", "50 %", None))
        self.Label0.setText(_translate("Module", "0 %", None))
        self.LabelRestantT.setText(_translate("Module", "Temps ou Mots restants", None))
        self.LabelRestantV.setText(_translate("Module", "25 / 30", None))
        self.LabelSMots.setText(_translate("Module", "s / Mots", None))
        self.LabelSMotsV.setText(_translate("Module", "2,01", None))
        self.LabelScore.setText(_translate("Module", "Score", None))
        self.LabelScoreV.setText(_translate("Module", "1281", None))
        self.LabelScoreT.setText(_translate("Module", "Scores", None))
        self.LabelBestT.setText(_translate("Module", "Meilleurs scores", None))
        self.BoutonStartPause.setText(_translate("Module", "Start / Pause", None))
        self.BoutonQuitter.setText(_translate("Module", "Quitter", None))
        self.LabelInfo.setText(_translate("Module", "Ici des informations sur le programme", None))
        self.LabelTexteDroite.setToolTip(_translate("Module", "<html><head/><body><p>22 caractères de chaque côté</p></body></html>", None))
        self.LabelTexteDroite.setText(_translate("Module", "Léo l", None))
        self.LabelTexteGauche.setText(_translate("Module", " cerf court dans la forêt", None))
        self.LabelTexteCentre.setText(_translate("Module", "e", None))
        self.LabelTapeDroit.setToolTip(_translate("Module", "<html><head/><body><p>8 caractères</p></body></html>", None))
        self.LabelTapeDroit.setText(_translate("Module", "Léo l", None))
        self.LabelTapeFleche.setToolTip(_translate("Module", "<html><head/><body><p>Il faut que l\'on fasse clignoter ce label si le caractère est juste ou faux</p></body></html>", None))
        self.LabelTapeFleche.setText(_translate("Module", "    <<<", None))
        self.LabelStatT.setText(_translate("Module", "Statistiques", None))
        self.LabelReussite.setText(_translate("Module", "Réussite", None))
        self.LabelErreurs.setText(_translate("Module", "Erreurs", None))
        self.Etoile2.setToolTip(_translate("Module", "<html><head/><body><p>Pour afficher des médailles / étoiles en fonction de la performance</p></body></html>", None))

